from typing import Any

import pandas as pd

from beaverfe.auto_parameters.distribution_n_scale import NormalizerSpaceGenerator
from beaverfe.auto_parameters.shared.space_generator import SearchSpace, SpaceGenerator
from beaverfe.model_profiler import ModelType
from beaverfe.pipeline_blocks import CANONICAL_ORDER, PipelineBlock
from beaverfe.transformations.utils import dtypes

# Blocks disabled per model type. Trees split optimally on raw values and are
# scale-invariant, so binning, outlier handling, splines (which only help
# models that benefit from smooth non-linear input mappings), and all
# normalisation are redundant for them.
_TREE_DISABLED: frozenset[PipelineBlock] = frozenset(
    {
        PipelineBlock.EXPAND_SPLINE,
        PipelineBlock.EXPAND_BINNING,
        PipelineBlock.CLEANSE_OUTLIERS,
        PipelineBlock.NORMALIZE,
    }
)

# Blocks previewed to discover generated columns for the dynamic-space pass
# below. EXPAND_SPLINE is deliberately excluded: SplineTransformation names
# its outputs positionally ("{col}__spline_{i}"), with no parameters encoded
# in the name, so the same key can hold different underlying data across
# trials depending on which spline config was chosen — violating Optuna's
# requirement that a parameter name have one fixed distribution per study.
# MathematicalOperations ("{a}__{op}__{b}") and NumericalBinning
# ("{col}__bins_{strategy}_{n_bins}") both encode their full recipe in the
# name, so a given name always maps to the same data and is safe to reuse.
_EXPANSION_BLOCKS: frozenset[PipelineBlock] = frozenset(
    {
        PipelineBlock.MISSING_INDICATOR,
        PipelineBlock.MISSING_HANDLER,
        PipelineBlock.EXTRACTION,
        PipelineBlock.EXPAND_CYCLICAL,
        PipelineBlock.EXPAND_MATH,
        PipelineBlock.EXPAND_BINNING,
    }
)

# Linear and distance-/margin-based models are sensitive to feature scale and
# outliers in a way tree models aren't.  "none" is dropped from NORMALIZE and
# CLEANSE_OUTLIERS options for these model types so Optuna is forced to pick
# an actual strategy per column instead of being free to skip normalisation
# and outlier handling entirely.
_SCALE_SENSITIVE_MODEL_TYPES: frozenset[str] = frozenset({"linear", "distance_based"})
_FORCE_NON_NONE_BLOCKS: frozenset[PipelineBlock] = frozenset(
    {PipelineBlock.NORMALIZE, PipelineBlock.CLEANSE_OUTLIERS}
)

# Generators re-applied to columns discovered mid-trial (after expansion
# blocks run), so generated numeric features become eligible for normalisation.
# CLEANSE_OUTLIERS is intentionally absent: with the v3 order it runs before
# EXPAND_MATH/EXPAND_SPLINE, so columns generated by those blocks never pass
# through it anyway — offering outlier spaces for them would be misleading.
_DYNAMIC_GENERATORS: list[tuple[PipelineBlock, SpaceGenerator]] = [
    (PipelineBlock.NORMALIZE, NormalizerSpaceGenerator()),
]

# Keys whose values are unhashable lists (structural metadata, not Optuna choices).
# These must never be passed to trial.suggest_categorical.
_STRUCTURAL_KEYS: frozenset[str] = frozenset(
    {
        "missing_indicator_features",
        "datetime_columns",
        "column_selection_candidates",
    }
)

# prefix_map used by _key_belongs_to_block — built once at module level.
_PREFIX_MAP: dict[PipelineBlock, list[str]] = {
    PipelineBlock.MISSING_INDICATOR: ["missing_indicator_"],
    PipelineBlock.MISSING_HANDLER: ["impute_"],
    PipelineBlock.EXTRACTION: ["datetime_"],
    PipelineBlock.EXPAND_CYCLICAL: ["cyclical_"],
    PipelineBlock.CLEANSE_OUTLIERS: ["outlier_"],
    PipelineBlock.EXPAND_MATH: ["math_ops"],
    PipelineBlock.EXPAND_SPLINE: ["spline_"],
    PipelineBlock.EXPAND_BINNING: ["binning_"],
    PipelineBlock.ENCODE: ["cat_enc_"],
    PipelineBlock.NORMALIZE: ["norm_"],
    PipelineBlock.REDUCE_DIM: ["dim_reduction_"],
}


class PipelineAssembler:
    """Translates an Optuna trial's parameter suggestions into a BeaverPipeline."""

    def assemble(
        self,
        trial: Any,
        spaces: SearchSpace,
        model_type: ModelType,
        X: pd.DataFrame | None = None,
        y: Any = None,
    ) -> list[dict]:
        """Sample parameters from trial and build transformer list.

        When `X` is provided, expansion blocks (extraction/cyclical/math
        ops/splines/binning) are previewed against this trial's own sampled
        choices to discover newly generated numeric columns, which are then
        offered to the downstream per-column blocks (outliers/distribute/
        scale/quantile) via additional `trial.suggest_categorical` calls
        within the same trial (Optuna's define-by-run pattern).
        """
        params = self._sample_params(trial, spaces, model_type)

        if X is not None:
            dynamic_spaces = self._discover_dynamic_spaces(
                params, spaces, model_type, X, y
            )
            for key, options in dynamic_spaces.items():
                # Structural keys (unhashable lists) must be injected directly
                # rather than passed to trial.suggest_categorical.
                if key in _STRUCTURAL_KEYS:
                    params[key] = (
                        options[0]
                        if isinstance(options, list) and len(options) == 1
                        else options
                    )
                    continue
                block = next(
                    (
                        b
                        for b in _FORCE_NON_NONE_BLOCKS
                        if self._key_belongs_to_block(key, b)
                    ),
                    None,
                )
                if block is not None:
                    options = self._resolve_options(options, block, model_type)
                params[key] = trial.suggest_categorical(key, options)
            spaces = {**spaces, **dynamic_spaces}

        return self._build_pipeline_dicts(params, spaces, model_type)

    def default_params(
        self, spaces: SearchSpace, model_type: ModelType
    ) -> dict[str, Any]:
        """ "none"-everywhere baseline params, for seeding an Optuna baseline
        trial. Respects the same per-model-type forced-non-"none" blocks as
        `_sample_params`, so a key that can't actually be "none" for this
        model type is left out rather than producing an invalid fixed value.
        """
        disabled = _TREE_DISABLED if model_type == "tree" else frozenset()
        params: dict[str, Any] = {}

        for block in CANONICAL_ORDER:
            if block in disabled:
                continue
            for key, options in spaces.items():
                if key in _STRUCTURAL_KEYS or not self._key_belongs_to_block(
                    key, block
                ):
                    continue
                if "none" in self._resolve_options(options, block, model_type):
                    params[key] = "none"

        return params

    def assemble_from_params(
        self, params: dict[str, Any], spaces: SearchSpace, model_type: ModelType
    ) -> list[dict]:
        """Deterministically build transformer list from an already-sampled params dict.

        No dynamic-space discovery is needed here: `params` (typically
        `study.best_params`) already contains every key suggested during the
        winning trial, including ones for dynamically-discovered columns —
        the per-block decoders key off `params` directly regardless of
        whether a column existed in the original search space.
        """
        return self._build_pipeline_dicts(params, spaces, model_type)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _discover_dynamic_spaces(
        self,
        params: dict[str, Any],
        spaces: SearchSpace,
        model_type: ModelType,
        X: pd.DataFrame,
        y: Any,
    ) -> SearchSpace:
        disabled = _TREE_DISABLED if model_type == "tree" else frozenset()
        if all(block in disabled for block, _ in _DYNAMIC_GENERATORS):
            # None of the downstream blocks we'd extend are even active for
            # this model type (e.g. every one of them is tree-disabled) —
            # skip the preview fit entirely.
            return {}

        # Local import: BeaverPipeline is only needed for this preview fit,
        # and importing it lazily keeps the module-level import graph simple.
        from beaverfe.beaver_pipeline import BeaverPipeline

        preview_dicts = [
            d
            for d in self._build_pipeline_dicts(params, spaces, model_type)
            if d.get("block") in _EXPANSION_BLOCKS
        ]
        if not preview_dicts:
            return {}

        preview_pipeline = BeaverPipeline(preview_dicts, order=CANONICAL_ORDER)
        try:
            X_expanded = preview_pipeline.fit_transform(X, y)
        except (ValueError, RuntimeError):
            return {}

        original_numeric = set(dtypes.numerical_columns(X))
        # Exclude __is_invalid flag columns (int8 indicators injected by
        # MathematicalOperations for div-by-zero results) from both the
        # generated-column list offered to dynamic generators and the
        # column_selection_candidates list offered to DimensionalityReduction.
        # These binary 0/1 columns are numeric in dtype but carry no
        # continuous-feature semantics, so offering them to scalers, outlier
        # detectors, or dimensionality-reduction methods is nonsensical.
        filtered_numeric_after_expansion = [
            col
            for col in dtypes.numerical_columns(X_expanded)
            if not col.endswith("__is_invalid")
        ]
        generated_columns = [
            col
            for col in filtered_numeric_after_expansion
            if col not in original_numeric
        ]
        if not generated_columns:
            return {}

        X_generated = X_expanded[generated_columns]

        dynamic_spaces: SearchSpace = {}
        for block, generator in _DYNAMIC_GENERATORS:
            if block in disabled:
                continue
            dynamic_spaces.update(generator.get_search_space(X_generated, y))

        # Refresh column_selection_candidates to include generated numeric
        # columns so that DimensionalityReduction's feature list is not limited
        # to the columns present in the original X before expansion blocks ran.
        original_candidates = spaces.get("column_selection_candidates")
        base_candidates: list[str] = (
            original_candidates[0] if original_candidates else []
        )
        updated_candidates = list(
            dict.fromkeys(
                base_candidates
                + [
                    c
                    for c in filtered_numeric_after_expansion
                    if c not in set(base_candidates)
                ]
            )
        )
        dynamic_spaces["column_selection_candidates"] = [updated_candidates]

        return dynamic_spaces

    def _sample_params(
        self, trial: Any, spaces: SearchSpace, model_type: ModelType
    ) -> dict[str, Any]:
        disabled = _TREE_DISABLED if model_type == "tree" else frozenset()
        params: dict[str, Any] = {}

        # Inject structural metadata directly — values are unhashable lists and
        # must never be passed to trial.suggest_categorical.
        for key in _STRUCTURAL_KEYS:
            if key in spaces:
                value = spaces[key]
                # The generator wraps the list in another list; unwrap one level.
                params[key] = (
                    value[0] if isinstance(value, list) and len(value) == 1 else value
                )

        for block in CANONICAL_ORDER:
            if block in disabled:
                continue
            for key, options in spaces.items():
                if key in _STRUCTURAL_KEYS:
                    continue
                if self._key_belongs_to_block(key, block):
                    options = self._resolve_options(options, block, model_type)
                    params[key] = trial.suggest_categorical(key, options)

        return params

    def _key_belongs_to_block(self, key: str, block: PipelineBlock) -> bool:
        for prefix in _PREFIX_MAP.get(block, []):
            if key.startswith(prefix) or key == prefix.rstrip("_"):
                return True
        return False

    def _resolve_options(
        self, options: list[Any], block: PipelineBlock, model_type: ModelType
    ) -> list[Any]:
        if (
            model_type in _SCALE_SENSITIVE_MODEL_TYPES
            and block in _FORCE_NON_NONE_BLOCKS
            and "none" in options
            and len(options) > 1
        ):
            return [option for option in options if option != "none"]
        return options

    def _collect_by_prefix(
        self,
        params: dict[str, Any],
        prefix: str,
        decode: Any = str,
    ) -> dict[str, Any]:
        """Strip `prefix` from every key in `params` that starts with it and
        has a non-"none" value, decoding each value via `decode`. Shared by
        the per-column block decoders below that all follow this exact
        iterate/strip-prefix/skip-"none" shape.
        """
        result: dict[str, Any] = {}
        for key, value in params.items():
            if not key.startswith(prefix) or value == "none":
                continue
            col = key[len(prefix) :]
            result[col] = decode(str(value))
        return result

    def _build_pipeline_dicts(
        self, params: dict[str, Any], spaces: SearchSpace, model_type: ModelType
    ) -> list[dict]:
        disabled = _TREE_DISABLED if model_type == "tree" else frozenset()
        transformers: list[dict] = []

        for block in CANONICAL_ORDER:
            if block in disabled:
                continue
            block_dicts = self._decode_block(block, params, spaces)
            transformers.extend(block_dicts)

        return transformers

    def _decode_block(
        self, block: PipelineBlock, params: dict[str, Any], spaces: SearchSpace
    ) -> list[dict]:
        if block == PipelineBlock.MISSING_INDICATOR:
            return self._decode_missing_indicator(params)
        if block == PipelineBlock.MISSING_HANDLER:
            return self._decode_missing_handler(params)
        if block == PipelineBlock.EXTRACTION:
            return self._decode_datetime(params)
        if block == PipelineBlock.EXPAND_CYCLICAL:
            return self._decode_cyclical(params)
        if block == PipelineBlock.EXPAND_MATH:
            return self._decode_math_ops(params)
        if block == PipelineBlock.EXPAND_SPLINE:
            return self._decode_spline(params)
        if block == PipelineBlock.EXPAND_BINNING:
            return self._decode_binning(params)
        if block == PipelineBlock.CLEANSE_OUTLIERS:
            return self._decode_outliers(params)
        if block == PipelineBlock.ENCODE:
            return self._decode_categorical(params)
        if block == PipelineBlock.NORMALIZE:
            return self._decode_normalize(params)
        if block == PipelineBlock.REDUCE_DIM:
            return self._decode_dim_reduction(params, spaces)
        return []

    # ------------------------------------------------------------------
    # Block decoders
    # ------------------------------------------------------------------

    def _decode_missing_indicator(self, params: dict[str, Any]) -> list[dict]:
        features = params.get("missing_indicator_features")
        if not features:
            return []
        return [
            {
                "name": "MissingValuesIndicator",
                "params": {"features": features},
                "block": PipelineBlock.MISSING_INDICATOR,
            }
        ]

    def _decode_missing_handler(self, params: dict[str, Any]) -> list[dict]:
        transformation_options: dict[str, str] = {}
        n_neighbors: dict[str, int] = {}

        for key, value in params.items():
            if not key.startswith("impute_") or value == "none":
                continue
            col = key[len("impute_") :]
            strategy, knn_n = self._decode_impute(col, str(value))
            transformation_options[col] = strategy
            if strategy == "knn" and knn_n is not None:
                n_neighbors[col] = knn_n

        if not transformation_options:
            return []

        return [
            {
                "name": "MissingValuesHandler",
                "params": {
                    "transformation_options": transformation_options,
                    "n_neighbors": n_neighbors or None,
                },
                "block": PipelineBlock.MISSING_HANDLER,
            }
        ]

    def _decode_impute(self, col: str, token: str) -> tuple[str, int | None]:
        if token.startswith("knn_"):
            n = int(token[4:])
            return "knn", n
        return token, None

    def _decode_datetime(self, params: dict[str, Any]) -> list[dict]:
        columns = params.get("datetime_columns")
        if not columns:
            return []
        return [
            {
                "name": "DateTimeTransformer",
                "params": {"features": columns},
                "block": PipelineBlock.EXTRACTION,
            }
        ]

    def _decode_cyclical(self, params: dict[str, Any]) -> list[dict]:
        transformation_options = self._collect_by_prefix(params, "cyclical_", int)

        if not transformation_options:
            return []

        return [
            {
                "name": "CyclicalFeaturesTransformer",
                "params": {"transformation_options": transformation_options},
                "block": PipelineBlock.EXPAND_CYCLICAL,
            }
        ]

    def _decode_math_ops(self, params: dict[str, Any]) -> list[dict]:
        operations: list[tuple[str, str, str]] = []
        seen: set[tuple[str, str, str]] = set()

        for key, value in params.items():
            if not key.startswith("math_ops_") or not value or value == "none":
                continue
            # value is encoded as "col_a__op__col_b"
            parts = str(value).split("__")
            if len(parts) != 3:
                continue
            col_a, op, col_b = parts
            op_tuple = (col_a, col_b, op)
            if op_tuple not in seen:
                seen.add(op_tuple)
                operations.append(op_tuple)

        if not operations:
            return []

        return [
            {
                "name": "MathematicalOperations",
                "params": {"operations_options": operations},
                "block": PipelineBlock.EXPAND_MATH,
            }
        ]

    def _decode_spline(self, params: dict[str, Any]) -> list[dict]:
        transformation_options = self._collect_by_prefix(
            params, "spline_", self._decode_spline_token
        )

        if not transformation_options:
            return []

        return [
            {
                "name": "SplineTransformation",
                "params": {"transformation_options": transformation_options},
                "block": PipelineBlock.EXPAND_SPLINE,
            }
        ]

    def _decode_spline_token(self, token: str) -> dict[str, Any]:
        parts = token.split("__")
        if len(parts) == 3:
            n_knots, degree, extrapolation = parts
            return {
                "n_knots": int(n_knots),
                "degree": int(degree),
                "extrapolation": extrapolation,
            }
        return {"n_knots": 5, "degree": 3, "extrapolation": "linear"}

    def _decode_binning(self, params: dict[str, Any]) -> list[dict]:
        transformation_options = self._collect_by_prefix(
            params, "binning_", self._decode_binning_token
        )

        if not transformation_options:
            return []

        return [
            {
                "name": "NumericalBinning",
                "params": {"transformation_options": transformation_options},
                "block": PipelineBlock.EXPAND_BINNING,
            }
        ]

    def _decode_binning_token(self, token: str) -> tuple[str, int]:
        parts = token.split("__")
        if len(parts) == 2:
            strategy, n_bins = parts
            return strategy, int(n_bins)
        return "quantile", 5

    def _decode_outliers(self, params: dict[str, Any]) -> list[dict]:
        transformation_options: dict[str, tuple[str, str]] = {}
        thresholds: dict[str, float] = {}
        iforest_params: dict[str, dict[str, float]] = {}

        for key, value in params.items():
            if not key.startswith("outlier_") or value == "none":
                continue
            col = key[len("outlier_") :]
            outlier_kwargs = self._decode_outlier_token(col, str(value))
            col_action, col_method = outlier_kwargs["transformation_options"][col]
            transformation_options[col] = (col_action, col_method)
            if "thresholds" in outlier_kwargs:
                thresholds[col] = outlier_kwargs["thresholds"][col]
            if "iforest_params" in outlier_kwargs:
                iforest_params[col] = outlier_kwargs["iforest_params"][col]

        if not transformation_options:
            return []

        return [
            {
                "name": "OutliersHandler",
                "params": {
                    "transformation_options": transformation_options,
                    "thresholds": thresholds or None,
                    "iforest_params": iforest_params or None,
                },
                "block": PipelineBlock.CLEANSE_OUTLIERS,
            }
        ]

    def _decode_outlier_token(self, col: str, token: str) -> dict[str, Any]:
        parts = token.split("__")
        if len(parts) == 3:
            action, method, param_str = parts
            param = float(param_str)
            kwargs: dict[str, Any] = {"transformation_options": {col: (action, method)}}
            if method == "iforest":
                kwargs["iforest_params"] = {col: {"contamination": param}}
            else:
                kwargs["thresholds"] = {col: param}
            return kwargs
        return {
            "transformation_options": {col: ("cap", "iqr")},
            "thresholds": {col: 1.5},
        }

    def _decode_categorical(self, params: dict[str, Any]) -> list[dict]:
        # "none" is never an offered option here, so no filtering needed for
        # it — but _collect_by_prefix's check is a no-op in that case anyway.
        transformation_options = self._collect_by_prefix(params, "cat_enc_")

        if not transformation_options:
            return []

        return [
            {
                "name": "CategoricalEncoding",
                "params": {"transformation_options": transformation_options},
                "block": PipelineBlock.ENCODE,
            }
        ]

    def _decode_normalize(self, params: dict[str, Any]) -> list[dict]:
        """Decode the unified normalisation block.

        Each "norm_{col}" key carries a value that encodes both the
        transformer family and its option, e.g. "scale__standard",
        "quantile__uniform", "nonlinear__yeo_johnson".
        Columns are dispatched to the correct transformer by inspecting
        the value prefix, then grouped into at most four transformer dicts.
        """
        nonlinear_options: dict[str, str] = {}
        normalize_options: dict[str, str] = {}
        scale_options: dict[str, str] = {}
        scale_quantile_range: dict[str, tuple[float, float]] = {}
        quantile_options: dict[str, str] = {}

        for key, value in params.items():
            if not key.startswith("norm_") or value == "none":
                continue
            col = key[len("norm_") :]
            value_str = str(value)
            if value_str.startswith("nonlinear__"):
                nonlinear_options[col] = value_str[len("nonlinear__") :]
            elif value_str.startswith("normalize__"):
                normalize_options[col] = value_str[len("normalize__") :]
            elif value_str.startswith("scale__"):
                scale_token = value_str[len("scale__") :]
                scaler, q_range = self._decode_scale_token(scale_token)
                scale_options[col] = scaler
                if q_range is not None:
                    scale_quantile_range[col] = q_range
            elif value_str.startswith("quantile__"):
                quantile_options[col] = value_str[len("quantile__") :]

        result: list[dict] = []
        if nonlinear_options:
            result.append(
                {
                    "name": "NonLinearTransformation",
                    "params": {"transformation_options": nonlinear_options},
                    "block": PipelineBlock.NORMALIZE,
                }
            )
        if normalize_options:
            result.append(
                {
                    "name": "Normalization",
                    "params": {"transformation_options": normalize_options},
                    "block": PipelineBlock.NORMALIZE,
                }
            )
        if scale_options:
            result.append(
                {
                    "name": "ScaleTransformation",
                    "params": {
                        "transformation_options": scale_options,
                        "quantile_range": scale_quantile_range or None,
                    },
                    "block": PipelineBlock.NORMALIZE,
                }
            )
        if quantile_options:
            result.append(
                {
                    "name": "QuantileTransformation",
                    "params": {"transformation_options": quantile_options},
                    "block": PipelineBlock.NORMALIZE,
                }
            )
        return result

    def _decode_scale_token(self, token: str) -> tuple[str, tuple[float, float] | None]:
        if token.startswith("robust__"):
            q_low = float(token[len("robust__") :])
            return "robust", (q_low, 100.0 - q_low)
        return token, None

    def _decode_dim_reduction(
        self, params: dict[str, Any], spaces: SearchSpace
    ) -> list[dict]:
        method = params.get("dim_reduction_method")
        n_components = params.get("dim_reduction_n_components")

        if not method or method == "none" or not n_components:
            return []

        # Retrieve candidate columns from the structural key injected by
        # ColumnSelectionSpaceGenerator; fall back to None if unavailable.
        # When expansion blocks are active this key is refreshed dynamically by
        # _discover_dynamic_spaces to include generated numeric columns, so the
        # feature list here includes any columns produced by EXPAND_MATH,
        # EXPAND_CYCLICAL, EXPAND_BINNING, etc.
        candidates = spaces.get("column_selection_candidates")
        features: list[str] | None = candidates[0] if candidates else None

        return [
            {
                "name": "DimensionalityReduction",
                "params": {
                    "method": str(method),
                    "n_components": int(n_components),
                    "features": features,
                },
                "block": PipelineBlock.REDUCE_DIM,
            }
        ]
