import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin


class MathematicalOperations(BaseEstimator, TransformerMixin):
    def __init__(self, operations_options=None, track_columns=False):
        self.operations_options = operations_options
        self.track_columns = track_columns

        self.tracked_columns = {}

    def fit(self, X, y=None):
        # No fitting required for this transformer, maintaining compatibility with scikit-learn API
        return self

    def transform(self, X, y=None):
        # Protect the caller's DataFrame — all mutations happen on this copy.
        X = X.copy()

        # Each operation is computed from the original input columns only (no
        # operation references a column generated by a previous operation in
        # the same call), so the collect-then-concat pattern is safe: we
        # accumulate result Series and join them once after the loop.
        new_cols: list[pd.Series] = []

        for col1, col2, operation in self.operations_options or []:
            new_column = f"{col1}__{operation}__{col2}"

            if operation == "add":
                result = X[col1] + X[col2]

            elif operation == "subtract":
                result = X[col1] - X[col2]

            elif operation == "multiply":
                result = X[col1] * X[col2]

            elif operation == "divide":
                result = X[col1] / X[col2]

            elif operation == "modulus":
                result = X[col1] % X[col2]

            elif operation == "hypotenuse":
                result = np.hypot(X[col1], X[col2])

            elif operation == "mean":
                result = (X[col1] + X[col2]) / 2

            elif operation == "power":
                result = np.power(X[col1], X[col2])

            elif operation == "min":
                result = np.minimum(X[col1], X[col2])

            elif operation == "max":
                result = np.maximum(X[col1], X[col2])

            elif operation == "log_ratio":
                result = np.log(X[col1] / X[col2])

            else:
                continue

            # Replace inf with NaN so both cases are handled uniformly.
            result = result.replace([np.inf, -np.inf], np.nan)
            result.name = new_column

            # Inject an indicator column for cells that are structurally
            # undefined (inf or NaN after the operation), so the signal is not
            # silently erased by the fillna below. This mirrors the pattern
            # used by MissingValuesIndicator for upstream missing values.
            nan_mask = result.isna()
            if nan_mask.any():
                flag_series = nan_mask.astype("int8")
                flag_series.name = f"{new_column}__is_invalid"
                new_cols.append(flag_series)

            # Keep fillna(0) so downstream scalers do not encounter NaN.
            new_cols.append(result.fillna(0))

            if self.track_columns:
                self.tracked_columns[new_column] = [col1, col2]

        # Single concat avoids per-iteration DataFrame fragmentation.
        if new_cols:
            X = pd.concat([X, *new_cols], axis=1)

        return X

    def fit_transform(self, X, y=None):
        return self.fit(X, y).transform(X, y)
